version: '3'

services:
  app:
    build: .
    
    ports:
      - "8000:8000"

    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/app/fastapi_app.db:delegated
